version: 2
jobs:
  node10:
    working_directory: ~/tregusti/episode-parser
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-10-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-10-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test

  node12:
    working_directory: ~/tregusti/episode-parser
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-12-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-12-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test

  node14:
    working_directory: ~/tregusti/episode-parser
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-14-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-14-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run test

workflows:
  version: 2
  nodes:
    jobs:
      - node10
      - node12
      - node14

# vim: sw=2 ts=2 expandtab
